//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_TOURDL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HOADON
    {
        public int ID_HoaDon { get; set; }
        public int SLTreEm { get; set; }
        public int TongTienTour { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime NgayDat { get; set; }
        public string TinhTrang { get; set; }
        public int SLNguoiLon { get; set; }
        public int TienKhuyenMai { get; set; }
        public int TienPhaiTra { get; set; }
        public string ID_SPTour { get; set; }
        public Nullable<int> ID_KH { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual SPTOUR SPTOUR { get; set; }
    }
}
