//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_ClientLayout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_ClientLayout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\ADMIN\AppData\Local\Temp\990B1CCD7982E1762B0E7CBEED6DEECAE3EC\2\DAPM_LT_TourDL\DAPM_TOURDL\Views\Shared\ClientLayout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\ADMIN\AppData\Local\Temp\990B1CCD7982E1762B0E7CBEED6DEECAE3EC\2\DAPM_LT_TourDL\DAPM_TOURDL\Views\Shared\ClientLayout.cshtml"
    __o = RenderBody();


#line default
#line hidden
}
}
}
